{{- if and .Values.gateway.enabled .Values.observability.enabled (eq .Values.observability.scrape.kind "PodMonitor") }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "ng-gateway.fullname" . }}-podmonitor
  labels:
    {{- include "ng-gateway.gateway.labels" . | nindent 4 }}
    {{- $k := .Values.observability.prometheusOperator.selectorLabelKey }}
    {{- $v := .Values.observability.prometheusOperator.selectorLabelValue }}
    {{- if and $k $v (not (hasKey (.Values.observability.scrape.labels | default dict) $k)) }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- with .Values.observability.scrape.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.observability.scrape.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ng-gateway.gateway.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      interval: {{ .Values.observability.scrape.interval }}
      scrapeTimeout: {{ .Values.observability.scrape.scrapeTimeout }}
      path: /metrics
{{- end }}
{{- end }}

