//! AP configuration file renderer.
//!
//! Generates three configuration files consumed by the systemd-managed AP services:
//! - `ap-env` — shell variables sourced by `ng-gateway-ap-setup.service`
//! - `hostapd.conf` — hostapd main configuration
//! - `dnsmasq-ap.conf` — dnsmasq DHCP/DNS for AP clients
//!
//! All files are written to `/etc/ng-gateway/` (or a configurable base directory).

use ng_gateway_error::{network::NetworkError, NGResult};
use std::path::{Path, PathBuf};
use tokio::fs;
use tracing::{debug, info};

/// Default configuration directory for AP files.
pub const AP_CONFIG_DIR: &str = "/etc/ng-gateway";

/// Configuration file names.
pub const AP_ENV_FILE: &str = "ap-env";
pub const HOSTAPD_CONF_FILE: &str = "hostapd.conf";
pub const DNSMASQ_AP_CONF_FILE: &str = "dnsmasq-ap.conf";

/// Resolved AP configuration ready for rendering.
pub struct ApRenderContext {
    pub interface: String,
    pub ssid: String,
    pub password: String,
    pub channel: u32,
    pub ip: String,
    pub prefix_length: u8,
    pub dhcp_range_start: String,
    pub dhcp_range_end: String,
    pub dhcp_lease_time: String,
    /// The primary Wi-Fi STA interface (used for NAT uplink in concurrent mode).
    pub sta_iface: String,
    /// The detected uplink interface (interface with default route).
    pub uplink_iface: String,
    /// Whether AP and STA are mutually exclusive (single card, no concurrency).
    pub exclusive: bool,
}

/// Render and write all three AP configuration files atomically.
///
/// Returns the list of written file paths.
pub async fn render_and_write_ap_config(
    ctx: &ApRenderContext,
    config_dir: &str,
) -> NGResult<Vec<PathBuf>> {
    let dir = Path::new(config_dir);
    fs::create_dir_all(dir).await.map_err(|e| {
        NetworkError::ApError(format!("Failed to create config dir {config_dir}: {e}"))
    })?;

    let ap_env = render_ap_env(ctx);
    let hostapd = render_hostapd_conf(ctx);
    let dnsmasq = render_dnsmasq_conf(ctx);

    let mut written = Vec::with_capacity(3);

    for (name, content) in [
        (AP_ENV_FILE, &ap_env),
        (HOSTAPD_CONF_FILE, &hostapd),
        (DNSMASQ_AP_CONF_FILE, &dnsmasq),
    ] {
        let path = dir.join(name);
        // Write to a temp file first, then rename for atomicity.
        let tmp_path = dir.join(format!(".{name}.tmp"));
        fs::write(&tmp_path, content).await.map_err(|e| {
            NetworkError::ApError(format!("Failed to write {}: {e}", tmp_path.display()))
        })?;
        fs::rename(&tmp_path, &path).await.map_err(|e| {
            NetworkError::ApError(format!("Failed to rename to {}: {e}", path.display()))
        })?;
        written.push(path);
    }

    info!(dir = config_dir, "AP configuration files rendered");
    debug!(ssid = %ctx.ssid, channel = ctx.channel, iface = %ctx.interface);

    Ok(written)
}

/// Backup existing AP configuration files for rollback.
pub async fn backup_ap_config(config_dir: &str) -> NGResult<()> {
    let dir = Path::new(config_dir);
    for name in [AP_ENV_FILE, HOSTAPD_CONF_FILE, DNSMASQ_AP_CONF_FILE] {
        let src = dir.join(name);
        let dst = dir.join(format!("{name}.bak"));
        if src.exists() {
            fs::copy(&src, &dst).await.map_err(|e| {
                NetworkError::ApError(format!("Failed to backup {}: {e}", src.display()))
            })?;
        }
    }
    Ok(())
}

/// Restore AP configuration files from backup.
pub async fn restore_ap_config(config_dir: &str) -> NGResult<()> {
    let dir = Path::new(config_dir);
    for name in [AP_ENV_FILE, HOSTAPD_CONF_FILE, DNSMASQ_AP_CONF_FILE] {
        let bak = dir.join(format!("{name}.bak"));
        let dst = dir.join(name);
        if bak.exists() {
            fs::rename(&bak, &dst).await.map_err(|e| {
                NetworkError::ApError(format!("Failed to restore {}: {e}", bak.display()))
            })?;
        }
    }
    info!(dir = config_dir, "AP configuration restored from backup");
    Ok(())
}

/// Render `ap-env` — shell variables sourced by the setup service.
fn render_ap_env(ctx: &ApRenderContext) -> String {
    format!(
        r#"# Auto-generated by ng-gateway — do not edit manually.
# Sourced by ng-gateway-ap-setup.service.

AP_IFACE="{iface}"
STA_IFACE="{sta_iface}"
UPLINK_IFACE="{uplink_iface}"
AP_EXCLUSIVE="{exclusive}"
AP_IP="{ip}"
AP_PREFIX="{prefix}"
AP_DHCP_START="{dhcp_start}"
AP_DHCP_END="{dhcp_end}"
"#,
        iface = ctx.interface,
        sta_iface = ctx.sta_iface,
        uplink_iface = ctx.uplink_iface,
        exclusive = ctx.exclusive,
        ip = ctx.ip,
        prefix = ctx.prefix_length,
        dhcp_start = ctx.dhcp_range_start,
        dhcp_end = ctx.dhcp_range_end,
    )
}

/// Render `hostapd.conf`.
fn render_hostapd_conf(ctx: &ApRenderContext) -> String {
    let channel = if ctx.channel == 0 { 6 } else { ctx.channel };

    format!(
        r#"# Auto-generated by ng-gateway — do not edit manually.
interface={iface}
driver=nl80211
ssid={ssid}
hw_mode=g
channel={channel}
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase={password}
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# Control interface for status queries
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
"#,
        iface = ctx.interface,
        ssid = ctx.ssid,
        channel = channel,
        password = ctx.password,
    )
}

/// Render `dnsmasq-ap.conf`.
///
/// Uses `bind-interfaces` + `listen-address` + `except-interface=lo` to ensure
/// dnsmasq only listens on the AP interface, avoiding conflicts with
/// `systemd-resolved` (which binds to `127.0.0.53:53`).
fn render_dnsmasq_conf(ctx: &ApRenderContext) -> String {
    format!(
        r#"# Auto-generated by ng-gateway — do not edit manually.
# DHCP + DNS for AP clients only.

interface={iface}
bind-interfaces
except-interface=lo
listen-address={ip}
dhcp-range={start},{end},{lease}
dhcp-option=6,{ip}

# Prevent dnsmasq from reading the host's /etc/resolv.conf
no-resolv
# Forward DNS queries to well-known public resolvers
server=8.8.8.8
server=1.1.1.1
"#,
        iface = ctx.interface,
        ip = ctx.ip,
        start = ctx.dhcp_range_start,
        end = ctx.dhcp_range_end,
        lease = ctx.dhcp_lease_time,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_ctx() -> ApRenderContext {
        ApRenderContext {
            interface: "wlan0_ap".to_string(),
            ssid: "NG-Gateway-ABCD".to_string(),
            password: "ng-gateway".to_string(),
            channel: 6,
            ip: "10.47.0.1".to_string(),
            prefix_length: 24,
            dhcp_range_start: "10.47.0.10".to_string(),
            dhcp_range_end: "10.47.0.200".to_string(),
            dhcp_lease_time: "12h".to_string(),
            sta_iface: "wlan0".to_string(),
            uplink_iface: "wlan0".to_string(),
            exclusive: false,
        }
    }

    #[test]
    fn test_render_hostapd_conf() {
        let conf = render_hostapd_conf(&test_ctx());
        assert!(conf.contains("interface=wlan0_ap"));
        assert!(conf.contains("ssid=NG-Gateway-ABCD"));
        assert!(conf.contains("channel=6"));
        assert!(conf.contains("wpa_passphrase=ng-gateway"));
    }

    #[test]
    fn test_render_dnsmasq_conf() {
        let conf = render_dnsmasq_conf(&test_ctx());
        assert!(conf.contains("interface=wlan0_ap"));
        assert!(conf.contains("dhcp-range=10.47.0.10,10.47.0.200,12h"));
        assert!(conf.contains("except-interface=lo"));
        assert!(conf.contains("listen-address=10.47.0.1"));
    }

    #[test]
    fn test_render_ap_env() {
        let env = render_ap_env(&test_ctx());
        assert!(env.contains("AP_IFACE=\"wlan0_ap\""));
        assert!(env.contains("AP_IP=\"10.47.0.1\""));
        assert!(env.contains("STA_IFACE=\"wlan0\""));
        assert!(env.contains("UPLINK_IFACE=\"wlan0\""));
        assert!(env.contains("AP_EXCLUSIVE=\"false\""));
    }

    #[test]
    fn test_render_ap_env_exclusive() {
        let mut ctx = test_ctx();
        ctx.exclusive = true;
        ctx.interface = "wlP2p33s0".to_string();
        ctx.sta_iface = "wlP2p33s0".to_string();
        let env = render_ap_env(&ctx);
        assert!(env.contains("AP_EXCLUSIVE=\"true\""));
        assert!(env.contains("AP_IFACE=\"wlP2p33s0\""));
    }
}
