#!/usr/bin/env bash
set -euo pipefail

# preremove.sh
#
# Best-effort cleanup of all NG Gateway resources on package removal.
#
# Cleanup scope:
# - Stop and disable all NG Gateway systemd services (AP + main)
# - Remove AP systemd unit files deployed by init-network.sh
# - Unmask system services (dnsmasq, hostapd) that were masked during install
# - Remove AP configuration files generated by init-network.sh
#
# We do NOT remove runtime data/config (/var/lib/ng-gateway, /etc/ng-gateway/gateway.toml)
# to avoid accidental data loss — the user must purge these manually.

config_dir="/etc/ng-gateway"

if command -v systemctl >/dev/null 2>&1; then
  # Stop and disable AP services first (reverse dependency order).
  # ap-setup's ExecStop handles virtual interface teardown and iptables NAT cleanup.
  for unit in ng-gateway-dnsmasq.service ng-gateway-hostapd.service ng-gateway-ap-setup.service; do
    systemctl stop "$unit" >/dev/null 2>&1 || true
    systemctl disable "$unit" >/dev/null 2>&1 || true
  done

  # Stop and disable the main gateway service.
  systemctl stop ng-gateway.service >/dev/null 2>&1 || true
  systemctl disable ng-gateway.service >/dev/null 2>&1 || true

  # Clean up AP systemd unit files deployed by init-network.sh.
  # These are copied to the system directory at install time, not managed by nfpm.
  # Check both deb (/lib/systemd/system) and rpm (/usr/lib/systemd/system) paths.
  for unit in ng-gateway-ap-setup.service ng-gateway-hostapd.service ng-gateway-dnsmasq.service; do
    rm -f "/lib/systemd/system/${unit}" 2>/dev/null || true
    rm -f "/usr/lib/systemd/system/${unit}" 2>/dev/null || true
  done

  # Unmask system services that were masked during install.
  # This restores dnsmasq and hostapd to their pre-install state so the user
  # can manage them normally after ng-gateway is removed.
  for svc in dnsmasq.service hostapd.service; do
    if systemctl is-masked "$svc" 2>/dev/null | grep -q masked; then
      systemctl unmask "$svc" 2>/dev/null || true
      echo "[preremove] Unmasked ${svc}"
    fi
  done

  systemctl daemon-reload >/dev/null 2>&1 || true
fi

# Remove AP configuration files generated by init-network.sh.
# These are auto-generated and safe to remove; user config (gateway.toml, env) is preserved.
for f in ap-env hostapd.conf dnsmasq-ap.conf; do
  rm -f "${config_dir}/${f}" 2>/dev/null || true
done

cat <<EOF

[preremove] NG Gateway services stopped and disabled.
[preremove] AP resources cleaned up (systemd units, AP configs, service masks).
[preremove] Preserved (manual removal required for full purge):
  - ${config_dir}/gateway.toml  (user configuration)
  - ${config_dir}/env           (environment overrides)
  - /var/lib/ng-gateway/        (runtime data, certs, drivers, plugins)

EOF

exit 0
