#[derive(Debug)]
#[allow(dead_code)]
pub enum CasbinCmd {
    Enforce(Vec<String>),
    AddPolicy(Vec<String>),
    AddPolicies(Vec<Vec<String>>),
    AddNamedPolicy(String, Vec<String>),
    AddNamedPolicies(String, Vec<Vec<String>>),
    AddGroupingPolicy(Vec<String>),
    AddGroupingPolicies(Vec<Vec<String>>),
    AddNamedGroupingPolicy(String, Vec<String>),
    AddNamedGroupingPolicies(String, Vec<Vec<String>>),
    RemovePolicy(Vec<String>),
    RemovePolicies(Vec<Vec<String>>),
    RemoveNamedPolicy(String, Vec<String>),
    RemoveNamedPolicies(String, Vec<Vec<String>>),
    RemoveGroupingPolicy(Vec<String>),
    RemoveGroupingPolicies(Vec<Vec<String>>),
    RemoveNamedGroupingPolicy(String, Vec<String>),
    RemoveNamedGroupingPolicies(String, Vec<Vec<String>>),
    RemoveFilteredNamedPolicy(String, usize, Vec<String>),
    RemoveFilteredNamedGroupingPolicy(String, usize, Vec<String>),
    AddRoleForUser(String, String, Option<String>),
    AddRolesForUser(String, Vec<String>, Option<String>),
    DeleteRoleForUser(String, String, Option<String>),
    DeleteRolesForUser(String, Option<String>),
    GetImplicitRolesForUser(String, Option<String>),
    GetImplicitPermissionsForUser(String, Option<String>),
    HasRole(String, String, Option<String>),
    HasRoles(String, Vec<String>, Option<String>),
    HasAnyRole(String, Vec<String>, Option<String>),
}

#[derive(Debug)]
#[allow(dead_code)]
pub enum CasbinResult {
    Enforce(bool),
    AddPolicy(bool),
    AddPolicies(bool),
    AddNamedPolicy(bool),
    AddNamedPolicies(bool),
    AddGroupingPolicy(bool),
    AddGroupingPolicies(bool),
    AddNamedGroupingPolicy(bool),
    AddNamedGroupingPolicies(bool),
    RemovePolicy(bool),
    RemovePolicies(bool),
    RemoveNamedPolicy(bool),
    RemoveNamedPolicies(bool),
    RemoveGroupingPolicy(bool),
    RemoveGroupingPolicies(bool),
    RemoveNamedGroupingPolicy(bool),
    RemoveNamedGroupingPolicies(bool),
    RemoveFilteredNamedPolicy(bool),
    RemoveFilteredNamedGroupingPolicy(bool),
    AddRoleForUser(bool),
    AddRolesForUser(bool),
    DeleteRoleForUser(bool),
    DeleteRolesForUser(bool),
    GetImplicitRolesForUser(Vec<String>),
    GetImplicitPermissionsForUser(Vec<Vec<String>>),
    HasRole(bool),
    HasRoles(bool),
    HasAnyRole(bool),
}
