//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4
//! Modified to support single gateway device credentials storage

use crate::{
    entities::NGEntity,
    enums::common::{DataType, EntityType},
};
use ng_gateway_macros::IntoActiveValue;
use ng_gateway_sdk::ActionModel;
use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "action")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Device ID
    pub device_id: i32,
    /// Name
    pub name: String,
    /// Command
    pub command: String,
    /// Inputs
    pub inputs: Parameters,
}

impl From<Model> for ActionModel {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            device_id: value.device_id,
            name: value.name,
            command: value.command,
            inputs: value.inputs.into(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, IntoActiveValue, Deserialize, FromJsonQueryResult)]
pub struct Parameters(pub Vec<Parameter>);

impl From<Parameters> for Vec<ng_gateway_sdk::Parameter> {
    fn from(value: Parameters) -> Self {
        value.0.into_iter().map(|p| p.into()).collect()
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Parameter {
    /// Name
    pub name: String,
    /// Key
    pub key: String,
    /// Data type
    pub data_type: DataType,
    /// Required
    pub required: bool,
    /// Default value
    pub default_value: Option<serde_json::Value>,
    /// Max value
    pub max_value: Option<f64>,
    /// Min value
    pub min_value: Option<f64>,
    /// Driver configuration
    pub driver_config: serde_json::Value,
}

impl From<Parameter> for ng_gateway_sdk::Parameter {
    fn from(value: Parameter) -> Self {
        Self {
            name: value.name,
            key: value.key,
            data_type: value.data_type.into(),
            required: value.required,
            default_value: value.default_value,
            max_value: value.max_value,
            min_value: value.min_value,
            driver_config: value.driver_config,
        }
    }
}

impl NGEntity for Model {
    fn entity_type(&self) -> EntityType {
        EntityType::Action
    }

    fn id(&self) -> Option<i32> {
        Some(self.id)
    }
}

impl NGEntity for ActiveModel {
    fn entity_type(&self) -> EntityType {
        EntityType::Action
    }

    fn id(&self) -> Option<i32> {
        self.id.to_owned().take()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device::Entity",
        from = "Column::DeviceId",
        to = "super::device::Column::Id"
    )]
    Device,
}

impl Related<super::device::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Device.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
