//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use crate::{
    entities::NGEntity,
    enums::common::{EntityType, Status},
};
use ng_gateway_sdk::{QueuePolicy, RetryPolicy};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "app")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub plugin_id: i32,
    pub name: String,
    pub description: Option<String>,
    pub config: serde_json::Value,
    pub retry_policy: RetryPolicy,
    pub queue_policy: QueuePolicy,
    pub status: Status,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

impl NGEntity for Model {
    fn entity_type(&self) -> EntityType {
        EntityType::App
    }

    fn id(&self) -> Option<i32> {
        Some(self.id)
    }

    fn status(&self) -> Option<Status> {
        None
    }
}

impl NGEntity for ActiveModel {
    fn entity_type(&self) -> EntityType {
        EntityType::App
    }

    fn id(&self) -> Option<i32> {
        self.id.to_owned().take()
    }

    fn status(&self) -> Option<Status> {
        self.status.to_owned().take()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plugin::Entity",
        from = "Column::PluginId",
        to = "super::plugin::Column::Id"
    )]
    Plugin,
    #[sea_orm(has_one = "super::app_sub::Entity")]
    AppSub,
}

impl Related<super::plugin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plugin.def()
    }
}

impl Related<super::app_sub::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppSub.def()
    }
}
impl ActiveModelBehavior for ActiveModel {}
