//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4
//! Modified to support single gateway device credentials storage

use crate::enums::credentials::CredentialsType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "credentials")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Type of credentials (ACCESS_TOKEN, BASIC, X509_CERTIFICATE)
    pub r#type: CredentialsType,
    /// PEM encoded certificate for X509 authentication
    pub certificate: Option<String>,
    /// Client ID for MQTT connection
    pub client_id: Option<String>,
    /// Username for authentication
    pub username: Option<String>,
    /// Password for authentication
    pub password: Option<String>,
    /// Access token for token-based authentication
    pub access_token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
