//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4
//! Modified to support single gateway device credentials storage

use crate::{
    entities::NGEntity,
    enums::common::{EntityType, Status},
};
use ng_gateway_sdk::DeviceModel;
use sea_orm::{entity::prelude::*, ActiveValue};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "device")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Channel ID
    pub channel_id: i32,
    /// Device Name
    pub device_name: String,
    /// Device Type
    pub device_type: String,
    /// Enabled
    pub status: Status,
    /// Driver configuration
    pub driver_config: Option<serde_json::Value>,
}

impl From<Model> for DeviceModel {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            channel_id: value.channel_id,
            device_name: value.device_name,
            device_type: value.device_type,
            status: value.status.into(),
            driver_config: value.driver_config,
        }
    }
}

impl NGEntity for Model {
    fn entity_type(&self) -> EntityType {
        EntityType::Device
    }

    fn id(&self) -> Option<i32> {
        Some(self.id)
    }

    fn status(&self) -> Option<Status> {
        Some(self.status)
    }
}

impl NGEntity for ActiveModel {
    fn entity_type(&self) -> EntityType {
        EntityType::Device
    }

    fn id(&self) -> Option<i32> {
        self.id.to_owned().take()
    }

    fn status(&self) -> Option<Status> {
        self.status.to_owned().take()
    }
}

impl ActiveModel {
    pub fn merge_with_model(self, mut model: Model) -> Model {
        if let ActiveValue::Set(v) = &self.channel_id {
            model.channel_id = *v;
        }
        if let ActiveValue::Set(v) = &self.device_name {
            model.device_name = v.clone();
        }
        if let ActiveValue::Set(v) = &self.device_type {
            model.device_type = v.clone();
        }
        if let ActiveValue::Set(v) = &self.status {
            model.status = *v;
        }
        if let ActiveValue::Set(v) = &self.driver_config {
            model.driver_config = v.clone();
        }
        model
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel::Column::Id"
    )]
    Channel,
    #[sea_orm(has_many = "super::point::Entity")]
    Point,
    #[sea_orm(has_many = "super::action::Entity")]
    Action,
}

impl Related<super::channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channel.def()
    }
}

impl Related<super::point::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Point.def()
    }
}

impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
