//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use crate::{
    entities::NGEntity,
    enums::common::{EntityType, OsArch, OsType, SourceType, Status},
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "driver")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub driver_type: String,
    pub source: SourceType,
    pub version: String,
    pub api_version: u32,
    pub sdk_version: String,
    pub os_type: OsType,
    pub os_arch: OsArch,
    pub size: i64,
    pub path: String,
    pub checksum: String,
    pub metadata: serde_json::Value,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

impl NGEntity for Model {
    fn entity_type(&self) -> EntityType {
        EntityType::Driver
    }

    fn id(&self) -> Option<i32> {
        Some(self.id)
    }

    fn status(&self) -> Option<Status> {
        None
    }
}

impl NGEntity for ActiveModel {
    fn entity_type(&self) -> EntityType {
        EntityType::Driver
    }

    fn id(&self) -> Option<i32> {
        self.id.to_owned().take()
    }

    fn status(&self) -> Option<Status> {
        None
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channel::Entity")]
    Channel,
}

impl Related<super::channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
