//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use crate::{
    entities::NGEntity,
    enums::{
        common::{EntityType, Status},
        menu::MenuType,
    },
};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub parent_id: i32,
    pub r#type: MenuType,
    pub path: Option<String>,
    pub component: Option<String>,
    pub sort: Option<i32>,
    pub title: Option<String>,
    pub icon: Option<String>,
    pub affix_tab: bool,
    pub keep_alive: bool,
    pub hide_in_menu: bool,
    pub hide_children_in_menu: bool,
    pub status: Status,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

impl NGEntity for Model {
    fn entity_type(&self) -> EntityType {
        EntityType::Menu
    }

    fn id(&self) -> Option<i32> {
        Some(self.id)
    }

    fn status(&self) -> Option<Status> {
        Some(self.status)
    }
}

impl NGEntity for ActiveModel {
    fn entity_type(&self) -> EntityType {
        EntityType::Menu
    }

    fn id(&self) -> Option<i32> {
        self.id.to_owned().take()
    }

    fn status(&self) -> Option<Status> {
        self.status.to_owned().take()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation::Relation::MenuRole.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::relation::Relation::MenuToSelf.def().rev())
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
