//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use downcast_rs::{impl_downcast, DowncastSync};

use crate::enums::common::{EntityType, Status};
pub mod action;
pub mod app;
pub mod app_ext;
pub mod app_sub;
pub mod branding;
pub mod casbin;
pub mod channel;
pub mod credentials;
pub mod device;
pub mod driver;
pub mod menu;
pub mod plugin;
pub mod point;
pub mod prelude;
pub mod relation;
pub mod role;
pub mod user;

impl_downcast!(sync NGEntity);
/// Provides a unified interface for all validatable entities
pub trait NGEntity: DowncastSync + Send + Sync + 'static {
    /// Returns the entity type
    fn entity_type(&self) -> EntityType;

    /// Returns the entity ID, or None for new entities
    fn id(&self) -> Option<i32> {
        None
    }

    /// Returns the entity status
    fn status(&self) -> Option<Status> {
        None
    }
}
