//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4
//! Modified to support single gateway device credentials storage

use crate::{
    entities::NGEntity,
    enums::common::{AccessMode, DataPointType, DataType, EntityType},
};
use ng_gateway_sdk::{PointModel, Transform};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "point")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Device ID
    pub device_id: i32,
    /// Name
    pub name: String,
    /// Key
    pub key: String,
    /// Type
    pub r#type: DataPointType,
    /// Data Type
    pub data_type: DataType,
    /// Access Mode
    pub access_mode: AccessMode,
    /// Unit
    pub unit: Option<String>,
    /// Min Value
    pub min_value: Option<f64>,
    /// Max Value
    pub max_value: Option<f64>,
    /// Logical data type for transform (optional).
    pub transform_data_type: Option<DataType>,
    /// Transform scale factor (optional).
    pub transform_scale: Option<f64>,
    /// Transform offset (optional).
    pub transform_offset: Option<f64>,
    /// Whether to negate after affine mapping.
    pub transform_negate: bool,
    /// Driver configuration
    pub driver_config: serde_json::Value,
}

impl From<Model> for PointModel {
    fn from(value: Model) -> Self {
        // Backward compatibility: if transform_scale is missing but legacy `scale` exists,
        // treat it as transform.scale.
        Self {
            id: value.id,
            device_id: value.device_id,
            name: value.name,
            key: value.key,
            r#type: value.r#type.into(),
            data_type: value.data_type.into(),
            access_mode: value.access_mode.into(),
            unit: value.unit,
            min_value: value.min_value,
            max_value: value.max_value,
            transform: Transform {
                transform_data_type: value.transform_data_type.map(Into::into),
                transform_scale: value.transform_scale,
                transform_offset: value.transform_offset,
                transform_negate: value.transform_negate,
            },
            driver_config: value.driver_config,
        }
    }
}

impl NGEntity for Model {
    fn entity_type(&self) -> EntityType {
        EntityType::Point
    }

    fn id(&self) -> Option<i32> {
        Some(self.id)
    }
}

impl NGEntity for ActiveModel {
    fn entity_type(&self) -> EntityType {
        EntityType::Point
    }

    fn id(&self) -> Option<i32> {
        self.id.to_owned().take()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device::Entity",
        from = "Column::DeviceId",
        to = "super::device::Column::Id"
    )]
    Device,
}

impl Related<super::device::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Device.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
