//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use crate::entities::{
    action::{
        ActiveModel as ActionActiveModel, Column as ActionColumn, Entity as Action,
        Model as ActionModel, Parameter, Parameters,
    },
    ai::{
        alarm_event::{
            ActiveModel as AlarmEventActiveModel, Column as AlarmEventColumn, Entity as AlarmEvent,
            Model as AlarmEventModel,
        },
        alarm_rule::{
            ActiveModel as AlarmRuleActiveModel, AlarmCondition, Column as AlarmRuleColumn,
            Entity as AlarmRule, Model as AlarmRuleModel,
        },
        algorithm::{
            ActiveModel as AlgorithmActiveModel, Column as AlgorithmColumn, Entity as Algorithm,
            Model as AlgorithmModel,
        },
        model::{
            ActiveModel as ModelActiveModel, Column as ModelColumn, Entity as Model, Labels,
            Model as ModelModel, TensorDesc, TensorDescs,
        },
        pipeline::{
            ActiveModel as PipelineActiveModel, AnnotationConfig, Column as PipelineColumn,
            Entity as Pipeline, Model as PipelineModel, NormalizationConfig, PostProcessorConfig,
            PreProcessorConfig, RegionOfInterest, RoiRegions,
        },
        pipeline_binding::{
            ActiveModel as PipelineBindingActiveModel, Column as PipelineBindingColumn,
            Entity as PipelineBinding, Model as PipelineBindingModel,
        },
        pipeline_stage::{
            ActiveModel as PipelineStageActiveModel, Column as PipelineStageColumn,
            Entity as PipelineStage, Model as PipelineStageModel, StageConfig,
        },
    },
    app::{ActiveModel as AppActiveModel, Column as AppColumn, Entity as App, Model as AppModel},
    app_ext::{
        ActiveModel as AppExtActiveModel, Column as AppExtColumn, Entity as AppExt,
        Model as AppExtModel,
    },
    app_sub::{
        ActiveModel as AppSubActiveModel, Column as AppSubColumn, Entity as AppSub,
        Ids as AppSubIds, Model as AppSubModel,
    },
    branding::{
        ActiveModel as BrandingActiveModel, Column as BrandingColumn, Entity as Branding,
        Model as BrandingModel,
    },
    casbin::{Column as CasbinColumn, Entity as Casbin, Model as CasbinModel},
    channel::{
        ActiveModel as ChannelActiveModel, Column as ChannelColumn, Entity as Channel,
        Model as ChannelModel,
    },
    credentials::{
        ActiveModel as CredentialsActiveModel, Column as CredentialsColumn, Entity as Credentials,
        Model as CredentialsModel,
    },
    device::{
        ActiveModel as DeviceActiveModel, Column as DeviceColumn, Entity as Device,
        Model as DeviceModel,
    },
    driver::{
        ActiveModel as DriverActiveModel, Column as DriverColumn, Entity as Driver,
        Model as DriverModel,
    },
    menu::{
        ActiveModel as MenuActiveModel, Column as MenuColumn, Entity as Menu, Model as MenuModel,
    },
    plugin::{
        ActiveModel as PluginActiveModel, Column as PluginColumn, Entity as Plugin,
        Model as PluginModel,
    },
    point::{
        ActiveModel as PointActiveModel, Column as PointColumn, Entity as Point,
        Model as PointModel,
    },
    relation::{
        ActiveModel as RelationActiveModel, Column as RelationColumn, Entity as Relation,
        Model as RelationModel,
    },
    role::{
        ActiveModel as RoleActiveModel, Column as RoleColumn, Entity as Role, Model as RoleModel,
    },
    user::{
        ActiveModel as UserActiveModel, Column as UserColumn, Entity as User, Model as UserModel,
    },
};
