//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use crate::{
    enums::{common::EntityType, relation::RelationType},
    initializer::SeedableTrait,
};
use sea_orm::{entity::prelude::*, Condition, IntoActiveModel};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "relation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub from_id: i32,
    pub from_type: EntityType,
    pub to_id: i32,
    pub to_type: EntityType,
    pub r#type: RelationType,
    pub additional_info: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    UserRole,
    RoleUser,
    RoleMenu,
    MenuRole,
    UserToSelf,
    UserFromSelf,
    RoleToSelf,
    RoleFromSelf,
    MenuToSelf,
    MenuFromSelf,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Relation::UserRole => Entity::belongs_to(super::role::Entity)
                .from(Column::ToId)
                .to(super::role::Column::Id)
                .on_condition(|_, _| {
                    Condition::all()
                        .add(Column::ToType.eq(EntityType::Role))
                        .add(Column::FromType.eq(EntityType::User))
                        .add(Column::Type.eq(RelationType::Contains))
                })
                .into(),
            Relation::RoleUser => Entity::belongs_to(super::user::Entity)
                .from(Column::ToId)
                .to(super::user::Column::Id)
                .on_condition(|_, _| {
                    Condition::all()
                        .add(Column::ToType.eq(EntityType::Role))
                        .add(Column::FromType.eq(EntityType::User))
                        .add(Column::Type.eq(RelationType::Contains))
                })
                .into(),
            Relation::RoleMenu => Entity::belongs_to(super::menu::Entity)
                .from(Column::ToId)
                .to(super::menu::Column::Id)
                .on_condition(|_, _| {
                    Condition::all()
                        .add(Column::ToType.eq(EntityType::Menu))
                        .add(Column::FromType.eq(EntityType::Role))
                        .add(Column::Type.eq(RelationType::Contains))
                })
                .into(),
            Relation::MenuRole => Entity::belongs_to(super::role::Entity)
                .from(Column::ToId)
                .to(super::role::Column::Id)
                .on_condition(|_, _| {
                    Condition::all()
                        .add(Column::ToType.eq(EntityType::Menu))
                        .add(Column::FromType.eq(EntityType::Role))
                        .add(Column::Type.eq(RelationType::Contains))
                })
                .into(),
            Relation::UserToSelf => Entity::belongs_to(super::user::Entity)
                .from(Column::ToId)
                .to(super::user::Column::Id)
                .into(),
            Relation::RoleToSelf => Entity::belongs_to(super::role::Entity)
                .from(Column::ToId)
                .to(super::role::Column::Id)
                .into(),
            Relation::UserFromSelf => Entity::belongs_to(super::user::Entity)
                .from(Column::FromId)
                .to(super::user::Column::Id)
                .into(),
            Relation::RoleFromSelf => Entity::belongs_to(super::role::Entity)
                .from(Column::FromId)
                .to(super::role::Column::Id)
                .into(),
            Relation::MenuToSelf => Entity::belongs_to(super::menu::Entity)
                .from(Column::ToId)
                .to(super::menu::Column::Id)
                .into(),
            Relation::MenuFromSelf => Entity::belongs_to(super::menu::Entity)
                .from(Column::FromId)
                .to(super::menu::Column::Id)
                .into(),
        }
    }
}

impl SeedableTrait for Model {
    type ActiveModel = ActiveModel;
    type Entity = Entity;

    fn get_active_model(&self) -> Self::ActiveModel {
        self.clone().into_active_model()
    }
}

impl ActiveModelBehavior for ActiveModel {}
