//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use crate::{
    entities::NGEntity,
    enums::{
        common::{EntityType, Status},
        role::RoleType,
    },
};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub code: String,
    pub sort: Option<i32>,
    pub r#type: RoleType,
    pub status: Status,
    pub additional_info: Option<Json>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

impl NGEntity for Model {
    fn entity_type(&self) -> EntityType {
        EntityType::Role
    }

    fn id(&self) -> Option<i32> {
        Some(self.id)
    }

    fn status(&self) -> Option<Status> {
        Some(self.status)
    }
}

impl NGEntity for ActiveModel {
    fn entity_type(&self) -> EntityType {
        EntityType::Role
    }

    fn id(&self) -> Option<i32> {
        self.id.to_owned().take()
    }

    fn status(&self) -> Option<Status> {
        self.status.to_owned().take()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation::Relation::RoleUser.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::relation::Relation::RoleToSelf.def().rev())
    }
}

impl Related<super::menu::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation::Relation::RoleMenu.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::relation::Relation::RoleFromSelf.def().rev())
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
