//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use crate::{
    entities::NGEntity,
    enums::common::{EntityType, Status},
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub username: String,
    pub password: String,
    pub nickname: String,
    pub avatar: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub status: Status,
    pub additional_info: Option<Json>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

impl NGEntity for Model {
    fn entity_type(&self) -> EntityType {
        EntityType::User
    }

    fn id(&self) -> Option<i32> {
        Some(self.id)
    }

    fn status(&self) -> Option<Status> {
        Some(self.status)
    }
}

impl NGEntity for ActiveModel {
    fn entity_type(&self) -> EntityType {
        EntityType::User
    }

    fn id(&self) -> Option<i32> {
        self.id.to_owned().take()
    }

    fn status(&self) -> Option<Status> {
        self.status.to_owned().take()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation::Relation::UserRole.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::relation::Relation::UserFromSelf.def().rev())
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
