//! Apache Kafka northward plugin for ng-gateway.
//!
//! This crate is compiled as a dynamic library (`cdylib`) and loaded by the gateway at runtime.
//! The exported symbols are generated by `ng_gateway_sdk::ng_plugin_factory!`.

pub mod config;
mod connector;
mod converter;
mod handle;
mod metadata;
mod session;

pub use config::KafkaPluginConfig;

use connector::KafkaConnector;
use converter::KafkaConverter;
use metadata::build_metadata;
use ng_gateway_sdk::ng_plugin_factory;

// Export factory and static metadata via C ABI for loader
ng_plugin_factory!(
    name = "Kafka",
    description = "Apache Kafka northward plugin",
    plugin_type = "kafka",
    component = KafkaConnector,
    metadata_fn = build_metadata,
    model_convert = KafkaConverter
);
