//! Apache Kafka northward plugin for ng-gateway.
//!
//! This crate is compiled as a dynamic library (`cdylib`) and loaded by the gateway at runtime.
//! The exported symbols are generated by `ng_gateway_sdk::ng_plugin_factory!`.

pub mod config;
mod factory;
mod metadata;
mod plugin;
mod supervisor;

pub use config::KafkaPluginConfig;

use factory::KafkaPluginFactory;
use metadata::build_metadata;
use ng_gateway_sdk::ng_plugin_factory;

// Export factory and static metadata via C ABI for loader
ng_plugin_factory!(
    name = "Kafka",
    description = "Apache Kafka northward plugin",
    plugin_type = "kafka",
    factory = KafkaPluginFactory,
    metadata_fn = build_metadata
);
